# Generated by Django 4.1.2 on 2022-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.IntegerField(choices=[(1, 'phone'), (2, 'facebook'), (3, 'email')]),
        ),
    ]
