# Generated by Django 4.1.2 on 2022-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[(1, 'phone'), (2, 'facebook'), (3, 'email')], max_length=50),
        ),
    ]
